### ISSUE TITLE
As an author, my site should look simple, stylish, professional.

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#10]

**Comment by panchtatvam** [comment]
Please share a list of websites that capture the features ( even a few ) you want in `ro.vu`. I will be able to search for relevant Hugo themes (free) and analyze for customization.

**Comment by jrovu** [comment]
Here’s one. I’ll search for a few others. 

https://tanzu.vmware.com/developer/

**Comment by jrovu** [comment]
here are some more sites, and what I like about them. I can go into more detail later. on mobile device right now. 

https://www.principles.com/. simple text style. important looking

https://boz.com/articles/worst-first 
simple style. accent colors are interesting 

https://jborichevskiy.com/posts/concentration-compromise/
dark, simple

https://www.hackingwithswift.com/

https://www.hackingwithswift.com/example-code/system/how-to-make-one-operation-wait-for-another-to-complete-using-adddependency

colors. purpose of site (mini lessons)


https://developer.apple.com/documentation/swiftui/managing-model-data-in-your-app
nearly perfect (dark mode)

https://untools.co/
structure. tags

**Comment by panchtatvam** [comment]
I have shortlisted the following based on the demo sites you provided:

- [Papermod](https://adityatelange.github.io/hugo-PaperMod/): **Highly recommended**
  - Simple
  - optimised for reading
  - dark mode available
  - type-to-search facility
  - easy to select tags display
  - better archive layout
  - Matches with your selection at
    - [boz](https://boz.com/articles/worst-first)
    - [jborichevskiy](https://jborichevskiy.com/posts/concentration-compromise/)
    - 
- [Tale](https://chesterhow.github.io/tale/) : **Alright**
  - Slight animations
  - Simple layout
  - Tags easy to view
- [Dolt](https://hugodoit.pages.dev/): **If you like documentation**
  - Content listing site with page level navigation similar to [Tanzu](https://tanzu.vmware.com/developer/)

Certain features not present in the selected theme can be tweaked by code, if required.

Please share feedback on the list.
Thank you

**Comment by jrovu** [comment]
Let’s use PaperMod.

**Comment by panchtatvam** [comment]
Using [papermod](https://github.com/adityatelange/hugo-PaperMod) for ro.vu.
Setting up development environment with theme.

**Comment by jrovu** [comment]
What is the URL for the dev/staging site?
