### ISSUE TITLE
As a reader, I should be able to search for content on the site. (Searchable Tags, titles, page content)

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#11]

**Comment by panchtatvam** [comment]
Implementing lunr search for this.

**Comment by panchtatvam** [comment]
Fixed config file for implementing fuse search. Will be implementing the remaining parts now.

**Comment by panchtatvam** [comment]
Search implemented as per the theme functionality. Please review at [demo page](https://staging-rovu.netlify.app/search/).

**Comment by panchtatvam** [comment]
Archive page added to allow content viewing on monthly basis.

**Comment by jrovu** [comment]
Did a search for “casa”. Got many pages coming - some that didn’t contain “casa”.

**Comment by panchtatvam** [comment]
It is using fuzzy search. We can tune it to be very specific only as per [these options](https://fusejs.io/api/options.html). Please let me know which options you like and I'll tune fuseJs search.

**Comment by jrovu** [comment]
Accepted. If I decide adjust settings, I’ll make a new issue.
