### ISSUE TITLE
As an author, The "Last Updated" date of a post should default to file modification or git commit, so I don't have to manually specify a date in the YAML.

### ISSUE THREAD

**Issue by panchtatvam** [jrovu/ro.vu_hugo#14]

**Comment by panchtatvam** [comment]
Trying fixing the automatic date issue, still issues. Working on it.

**Comment by panchtatvam** [comment]
Git commits setup time now.

**Comment by panchtatvam** [comment]
Automatic timestamping works for posts without any dates. All no date posts now have date created timestamp added by their git commits. [Demo site](https://staging-rovu.netlify.app/).
Please review @jrovu

**Comment by jrovu** [comment]
Can you link me to a page where the date is pulled in from git commit

**Comment by panchtatvam** [comment]
Automatic date set by git commit in many [such](https://staging-rovu.netlify.app/passions/family/traditions/) posts.

**Comment by jrovu** [comment]
Thanks. Accepted.
