### ISSUE TITLE
Issue: As an author, it's annoying to have to commit every change manually. I wish it were like Apple Notes, where the content continuously syncs.

### ISSUE THREAD

**Issue by panchtatvam** [jrovu/ro.vu_hugo#17]

**Comment by panchtatvam** [comment]
Sync can only work via CMS like Netlify or Forestry. Apart from that git push is required. I suggest to setup at Forestry for CMS since you have chosen to work with Amazon hosting. Working on workflow for this to give proper suggestion.

**Comment by panchtatvam** [comment]
Auto sync won't work as such but with use of [Netlify CMS](https://www.netlifycms.org/) you can run the website CMS on your local computer as well, with internet connectvity, without the need to start a Hugo server. 
Netlify CMS will load the necessary files to be able to edit the content and with each save the content will be uploaded to Netlify servers for update and sync.

For now you are using Amazon AWS. The site deployment will have to move to Netlify for this to work.

Waiting for your thoughts on this @jrovu

**Comment by jrovu** [comment]
Let's hold off for now until I've had time to play with system.
