### ISSUE TITLE
Archive page for ease of content viewing on monthly basis for posts with date manually entered

### ISSUE THREAD

**Issue by panchtatvam** [jrovu/ro.vu_hugo#22]

**Comment by panchtatvam** [comment]
Archive [page](https://staging-rovu.netlify.app/archives/) added

**Comment by jrovu** [comment]
Thanks. Should I see more content? Only see a few pages.

**Comment by panchtatvam** [comment]
Only pages with coded dates can be read by this. If you add dates to pages they will start showing. git commit auto created dates can't be read by Hugo as such as they are created post commit.

**Comment by panchtatvam** [comment]
I'll be working to make this work for automatic dates too.

**Comment by panchtatvam** [comment]
Seems to work only for posts with date set in YAML. Sections to be seen have to be manually coded at `mainSections` param in `config.yaml` as per this [guide](https://gohugo.io/functions/where/#mainsections). Please [review](https://staging-rovu.netlify.app/archives/) @jrovu

**Comment by jrovu** [comment]
Thanks. Looks good. Accepted.
