### ISSUE TITLE
As a reader, I should be able to navigate from the content page to the github page, so that I can edit / suggest modifications for the content.

### ISSUE THREAD

**Issue by panchtatvam** [jrovu/ro.vu_hugo#23]

**Comment by panchtatvam** [comment]
Posts can be edited using the `Suggest changes` link below the post title. This is a link to the page file in the git repo connected. This setting can be done using the `editPost` param in `config.toml`. For now I have set to the final repository so the updates won't be reflected in the demo site.

**Comment by jrovu** [comment]
This looks good. Accepted.
