### ISSUE TITLE
As a visitor, I should not see the Hugo or theme branding in footer

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#24]
Remove

 · Powered by Hugo · Theme PaperMod

**Comment by panchtatvam** [comment]
Will have to credit the theme owner, so a credit page will be added with list to technology used. It is good to be thankful on internet.

**Comment by jrovu** [comment]
Perfect. “About this site”. all the tech & ppl involved.

**Comment by jrovu** [comment]
To be more clear:
- Remove Hugo & Theme links from footer
- Add to "About this site" content page. I will build out this page with further content on the tech stack.

**Comment by panchtatvam** [comment]
[About this site](https://staging-rovu.netlify.app/about-this-site) page created.
Please review @jrovu

**Comment by jrovu** [comment]
Looks great. Thanks. Accepted.
