### ISSUE TITLE
As a visitor, I should see “Suggest changes” at the bottom of the page (instead of top)

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#25]

**Comment by panchtatvam** [comment]
Will move `suggest edit` at the bottom of the post.

**Comment by panchtatvam** [comment]
Moved to footer with updates in :
- color ( `secondary-color` as used by the theme for consistency of post meta)
- text ( changed to `Edit this post`) to be more clear in meaning

Please review @jrovu

**Comment by jrovu** [comment]
I don’t see this @ https://staging-rovu.netlify.app/passions/life-improvement/decisions/decisions/

**Comment by panchtatvam** [comment]
It is at the bottom of the post as `Edit this post`
Please review @jrovu 
![Uploading Screenshot 2021-07-21 at 19-33-21 How to Make Decisions.png…]()

**Comment by jrovu** [comment]
![DC28CD2C-52A2-421A-9FB8-6181AC501E38](https://user-images.githubusercontent.com/244539/126518829-f6a3c4bb-b4d0-4ea5-bae4-ee265cfc8aa6.jpeg)


I see it. Please update the CSS on Dark mode to make it more visible.

**Comment by panchtatvam** [comment]
Fixed for dark mode. Please [review](https://staging-rovu.netlify.app/passions/life-improvement/decisions/decisions/) @jrovu

**Comment by jrovu** [comment]
Looks good. Accepted.
