### ISSUE TITLE
As a visitor, I should be able to visit Home by (1) clicking the site title, (2) bread crumb. Delete the Home link in the Nav bar. 

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#26]
![1CE75EA2-A6A9-4C7C-99F8-A477425EC959](https://user-images.githubusercontent.com/244539/126187254-5ce9dce7-594a-4ba4-99a3-017701d79a64.jpeg)

too many Homes

**Comment by panchtatvam** [comment]
Will remove home from navbar. Some pages don't show the site title. It is a bug. Will be fixing it.

**Comment by panchtatvam** [comment]
- Home link removed from navbar
- Bug for without markdown marked posts fixed. All pages show header now from the partial cached

Please review @jrovu

**Comment by jrovu** [comment]
Accepted.
