### ISSUE TITLE
As a visitor, it should clear the “2 min” means reading time. 

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#27]
What do think of:

Title
Last updated: YYYY-MM-DD by JRO
Estimated read time: 2 min

**Comment by panchtatvam** [comment]
This seems fine. Gives more information to the reader. I'll implement this.

**Comment by panchtatvam** [comment]
Last updated UX improvements done.
Please review @jrovu 
![Screenshot 2021-07-21 at 20-09-24 How to Make Decisions](https://user-images.githubusercontent.com/1580970/126507598-82d80047-9366-49f3-aa0c-8d0906829ebc.png)

**Comment by jrovu** [comment]
This looks great. Thank you. Accepted!

PS: When putting issues up for acceptance, would you please provide a test URL in the comment? Makes it easier for me to quickly verify when on my phone. Thx!
