### ISSUE TITLE
As a visitor, I can click the magnifying glass icon in the top-right of the screen to search

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#28]
-  add persistent magnifying glass to top right
- clicking it should keep visitor on same page (dont navigate to a search page)
- an input field appears
- as user types, top-5 autocomplete results appear
- hitting enter will search for the string in the input field, navigate to search results

**Comment by panchtatvam** [comment]
Will have to code the required icon menu option for search. On it.

**Comment by panchtatvam** [comment]
If search is added as an AJAX call icon in navigation bar then [index.json](https://staging-rovu.netlify.app/index.json) will have to be loaded at every page. `Index.json` works as the repository of site search params. For this reason there is a dedicated search page so this payload is not loaded at every page load.

I recommend to keep the search page and not use the magnifying glass AJAX loading option. Please review @jrovu

**Comment by jrovu** [comment]
I agree with your concerns. Let's keep search on its own page for now.
