### ISSUE TITLE
As a visitor, I can see all of the navigation bar items on the screen at once without needing to scroll

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#29]
currently, nav bar items are cut off

![82A8F584-6A72-4BB5-A70E-D516AE8845F6](https://user-images.githubusercontent.com/244539/126188664-bd1bcec0-d5da-4a6c-8be6-53543c583ca3.jpeg)

**Comment by panchtatvam** [comment]
Menu will have to be made responsive for smaller screens so clicking a menu opener will open the full menu vertically. The theme doesn't support this, I'll have to code this.

**Comment by jrovu** [comment]
"Hamburger menu" is OK. 

Another option: Make the box containing the nav take up 100% of width of screen, and allow the nav items to flow into a second line. 

Like:

Nav1, Nav2, Nav3
LongNav4, Nav5

I will use shorter-named nav items anyway... but I want the styles setup so nothing runs off the right side of screen. (same with content, if possible)

**Comment by panchtatvam** [comment]
- Used the suggestion by you and added a `flex-wrap`
- Added a horizontal line to demarcate nav from content

Please review @jrovu at [demo](https://staging-rovu.netlify.app/)

**Comment by jrovu** [comment]
Looks ok. 

- Delete “JRO Dashboard” from nav
- Delete “Search” from nav
- Add Magnifying glass icon to top-right of window, linking to search. Aligned with the Ro.VU 
- (if simple), put the Lightmode/darknode icon to top right of screen, along with search
—
RO.vu <— aligned left / aligned right ——-> ☀️🔎

[Passions] [Projects] [About]
—

let me know if that’s not clear. thanks!

**Comment by panchtatvam** [comment]
- JRO Dashboard removed
- Search replaced with icon with tooltip `Search`
- Dark/light mode toggle shifted to right with tooltip
- Menu items rearranged
Please review @jrovu

**Comment by jrovu** [comment]
Accepted.
