### ISSUE TITLE
As a visitor, I can see the page’s tags near the title. 

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#30]
put tags at top of page

lets try

title
tags
- date
- read time

(i’m not sure if I want tags above or below dates/read time…)

**Comment by panchtatvam** [comment]
Tags will be better below the date as they can be many.

**Comment by panchtatvam** [comment]
Tags placed below title and post meta. Please [review](https://staging-rovu.netlify.app/passions/life-improvement/decisions/decisions/).

**Comment by jrovu** [comment]
Accepted. Thanks.
