### ISSUE TITLE
As a visitor, I can see the RO.Vu logo

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#34]
Can't see the RO.VU branding on top-left of the pages

![image](https://user-images.githubusercontent.com/244539/126841124-f8d845aa-9678-411e-9baa-b15b322335e6.png)

**Comment by panchtatvam** [comment]
It is a bug for the staging site. Works well for [live site](https://ro.vu/). Please review @jrovu

**Comment by jrovu** [comment]
looks good. thx.
