### ISSUE TITLE
As a visitor, when I am on the Homepage, I see <text>

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#35]
(1) Home page Content:
---
# RO.Vu
Welcome to RO.VU Knowledge Base
---

(2)  Please remove the Twitter, Stackoverflow, Github logos

(3) Question: Where is home page content stored in Hugo?

**Comment by panchtatvam** [comment]
- Updated content. Removed social icons. Please [review](https://staging-rovu.netlify.app/) @jrovu 
- Home page content is rendered from `list.html` ([repo file](https://github.com/jrovu/ro.vu_hugo/blob/master/themes/papermod/layouts/_default/list.html)) in the current theme as per the [homepage lookup order](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-home-page)

**Comment by jrovu** [comment]
Updated thoughts on homepage…. I’d like to see how this looks….

—-
Hi there 👋
Welcome to RO.VU Knowledge Base

< Tag cloud (no “Tags” title), with tags sorted from number of pages descending. >

—-
 
See content from https://staging-rovu.netlify.app/tags/. 
output that tag cloud, but sort them by tags with most pages to fewest.

**Comment by panchtatvam** [comment]
Added list of tags to [homepage](https://staging-rovu.netlify.app/) with `no tags` link as well. Tags here can't be manipulated as the [tags page](https://staging-rovu.netlify.app/tags/) as they are limited by [Hugo functionality](https://gohugo.io/variables/taxonomy/#example-usage-of-sitetaxonomies). I can only create a list of them.

Please review @jrovu

**Comment by jrovu** [comment]
Looks good. I created a user story #40 for a small change to this.
