### ISSUE TITLE
As a visitor, when I am on the home page, and I am seeing the list of tags, I should see "Untagged content" as the LAST item on the list

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#40]
Currently on https://staging-rovu.netlify.app/: I see "No tags" as the first tag in the tag cloud
Desired state: [tag1] [tag2]...[tag10] [Untagged Content]

**Comment by panchtatvam** [comment]
Moved `untagged content` to last. Please [review](https://staging-rovu.netlify.app/) @jrovu

**Comment by jrovu** [comment]
accepted
