### ISSUE TITLE
As a visitor, when I look at the site footer, I don't see the Share content widget

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#41]
Current state: 
- At the footer, on content pages, I see Twitter, Linked in, etc

Desired state:
- This widget is disabled/hidden

Note:
- It's too distracting right now

**Comment by panchtatvam** [comment]
Social share icons disabled. Please [review](https://staging-rovu.netlify.app/passions/life-improvement/decisions/decisions/) @jrovu

**Comment by jrovu** [comment]
accepted
