### ISSUE TITLE
As a reader, when I click on "Passions", I should see a list of all of my Passions (tags?), and within each Passion, I should see a list of links to all content associated with that passion (tags)

### ISSUE THREAD

**Issue by jrovu** [jrovu/ro.vu_hugo#9]
/passions/ page

- Loop thru all subdirectories in /passions/ (e.g. "/books"). Use this as a Passion section header. 
- For each Passion, loop thru all the children page content. Create a list of linked content which exists below the respective passion's section header

directory:
- Passions/
-- /Dance/
---/Salsa
----- combinations.md
----- music.md

output:

# Passions
### Salsa
* Combinations
* Music

**Comment by panchtatvam** [comment]
Creating flow using sub directory structure. Work in progress.

**Comment by panchtatvam** [comment]
Researched on the issue. Have not been able to find any satisfactory result after 3 hours of research. Delegating issue to TODO.

**Comment by jrovu** [comment]
How about this:

**User Story:** As an author, when I add "page-type: passion" to a page's YAML, then I see that page appear in the alphabetized list of links to at /passions/
**Techical:**  /passions/ is an automatically generated list, which outputs linked titles of all pages in the site with YAML page-type: passion

**User story:** As an author, when I add "page-type: passion" to a page's YAML, and I add "tags: [foo, bar]", then Pages which have been Tagged "foo" OR "bar" will be listed in the "Related Content" heading, under the Page's main content.
**Technical:**: 
- There is a new PAGE TYPE called "passion". 
- - When a page's page-type is set to "passion", then a dynamic content block called "Related Content". appears under the page's main content. 
- The "Related Content" dynamic content block queries the Tags (e.g. "page-type: passion; tags: [salsa, dance]") to determine Current Page's Tags. Then, the "Related Content" dynamic content block will display a List of Links containing All Pages in the Site, which are Tagged with Current Page's Tags. 
- The "Related Content" block outputs links (1) grouped by a subheader of the Tag, (2) alphabetically-sorted list of the linked pages

Any feedback?

**Comment by panchtatvam** [comment]
I'm still working on this. Reverting within 24 hours.

**Comment by panchtatvam** [comment]
Shows a tag cloud of subsections / subfolders which can then be browsed to move further down. To make this work, a folder has to be made a section by placeing an `_index.md` file in it. Please note the underscore before the name. The file needs to contain two YAML params: `name` and `date`. You can copy paste the already available `_index.md` files in other folders I have placed like [here](https://github.com/panchtatvam/ro.vu_hugo/blob/staging/content/passions/acting/_index.md). This makes the folder a section and now will show in the parent section page like this:
Parent: [Passions page](https://staging-rovu.netlify.app/passions/)
Subfolders shown: Acting, Animals, Art ...
More subfolder: Akash in [Acting](https://staging-rovu.netlify.app/passions/acting/)

Please review @jrovu

**Comment by jrovu** [comment]
Subjections/folders - love this idea. I clicked around, it seems to work great. Accepted. Got some other feedback, I'll make user stories for them.
